"""create example models

Revision ID: a839bf3055f2
Revises:
Create Date: 2026-09-02 05:36:48.655307

Review upgrade() and downgrade() before applying this migration.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a839bf3055f2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('examples',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('svg_path', sa.String(length=255), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_example_logo_slug'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    with op.batch_alter_table('example_logo', schema=None) as batch_op:
        batch_op.create_index('ix_example_logo_country_available', ['country_code', 'is_available'], unique=False)
        batch_op.create_index('ix_example_logo_name', ['name'], unique=False)

    op.create_table('example_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cpu_cores', sa.SmallInteger(), nullable=False),
    sa.Column('memory_gb', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('bandwidth_mbps', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('bandwidth_mbps > 0', name='ck_example_server_bandwidth'),
    sa.CheckConstraint('cpu_cores > 0', name='ck_example_server_cpu_cores'),
    sa.CheckConstraint('memory_gb > 0', name='ck_example_server_memory_gb'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_example_server_name'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    with op.batch_alter_table('example_server', schema=None) as batch_op:
        batch_op.create_index('ix_example_server_region', ['region'], unique=False)
        batch_op.create_index('ix_example_server_status', ['status'], unique=False)

    op.create_table('example_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_example_tag_name'),
    sa.UniqueConstraint('slug', name='uq_example_tag_slug'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    op.create_table('example_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_example_team_slug'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    with op.batch_alter_table('example_team', schema=None) as batch_op:
        batch_op.create_index('ix_example_team_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_example_team_region', ['region'], unique=False)

    op.create_table('example_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('budget >= 0', name='ck_example_project_budget'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_example_project_progress'),
    sa.ForeignKeyConstraint(['team_id'], ['example_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_example_project_slug'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    with op.batch_alter_table('example_project', schema=None) as batch_op:
        batch_op.create_index('ix_example_project_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_example_project_priority', ['priority'], unique=False)
        batch_op.create_index('ix_example_project_team_status', ['team_id', 'status'], unique=False)

    op.create_table('example_server_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.Column('cpu_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('memory_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('upload_mbps', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('download_mbps', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cpu_percent >= 0 AND cpu_percent <= 100', name='ck_example_metric_cpu'),
    sa.CheckConstraint('download_mbps >= 0', name='ck_example_metric_download'),
    sa.CheckConstraint('memory_percent >= 0 AND memory_percent <= 100', name='ck_example_metric_memory'),
    sa.CheckConstraint('upload_mbps >= 0', name='ck_example_metric_upload'),
    sa.ForeignKeyConstraint(['server_id'], ['example_server.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    with op.batch_alter_table('example_server_metric', schema=None) as batch_op:
        batch_op.create_index('ix_example_server_metric_server_sampled', ['server_id', 'sampled_at'], unique=False)

    op.create_table('example_stream_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['logo_id'], ['example_logo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_example_stream_profile_name'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    with op.batch_alter_table('example_stream_profile', schema=None) as batch_op:
        batch_op.create_index('ix_example_stream_profile_logo_id', ['logo_id'], unique=False)
        batch_op.create_index('ix_example_stream_profile_status', ['status'], unique=False)

    op.create_table('example_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('document_path', sa.String(length=255), nullable=False),
    sa.Column('preview_path', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['example_project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    with op.batch_alter_table('example_asset', schema=None) as batch_op:
        batch_op.create_index('ix_example_asset_project_id', ['project_id'], unique=False)

    op.create_table('example_project_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['example_project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['example_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tag_id', name='uq_example_project_tag_pair'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    with op.batch_alter_table('example_project_tag', schema=None) as batch_op:
        batch_op.create_index('ix_example_project_tag_tag_id', ['tag_id'], unique=False)

    op.create_table('example_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('estimated_hours IS NULL OR estimated_hours >= 0', name='ck_example_task_estimated_hours'),
    sa.CheckConstraint('position >= 0', name='ck_example_task_position'),
    sa.ForeignKeyConstraint(['project_id'], ['example_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    info={'oldman_app_label': 'examples', 'oldman_managed': True}
    )
    with op.batch_alter_table('example_task', schema=None) as batch_op:
        batch_op.create_index('ix_example_task_due_at', ['due_at'], unique=False)
        batch_op.create_index('ix_example_task_priority', ['priority'], unique=False)
        batch_op.create_index('ix_example_task_project_status_position', ['project_id', 'status', 'position'], unique=False)

    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_logo', 'examples', TRUE, 'a839bf3055f2')")
    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_server', 'examples', TRUE, 'a839bf3055f2')")
    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_tag', 'examples', TRUE, 'a839bf3055f2')")
    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_team', 'examples', TRUE, 'a839bf3055f2')")
    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_project', 'examples', TRUE, 'a839bf3055f2')")
    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_server_metric', 'examples', TRUE, 'a839bf3055f2')")
    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_stream_profile', 'examples', TRUE, 'a839bf3055f2')")
    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_asset', 'examples', TRUE, 'a839bf3055f2')")
    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_project_tag', 'examples', TRUE, 'a839bf3055f2')")
    op.execute("INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('example_task', 'examples', TRUE, 'a839bf3055f2')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_task' AND app_label = 'examples'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_project_tag' AND app_label = 'examples'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_asset' AND app_label = 'examples'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_stream_profile' AND app_label = 'examples'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_server_metric' AND app_label = 'examples'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_project' AND app_label = 'examples'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_team' AND app_label = 'examples'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_tag' AND app_label = 'examples'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_server' AND app_label = 'examples'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'example_logo' AND app_label = 'examples'")
    with op.batch_alter_table('example_task', schema=None) as batch_op:
        batch_op.drop_index('ix_example_task_project_status_position')
        batch_op.drop_index('ix_example_task_priority')
        batch_op.drop_index('ix_example_task_due_at')

    op.drop_table('example_task')
    with op.batch_alter_table('example_project_tag', schema=None) as batch_op:
        batch_op.drop_index('ix_example_project_tag_tag_id')

    op.drop_table('example_project_tag')
    with op.batch_alter_table('example_asset', schema=None) as batch_op:
        batch_op.drop_index('ix_example_asset_project_id')

    op.drop_table('example_asset')
    with op.batch_alter_table('example_stream_profile', schema=None) as batch_op:
        batch_op.drop_index('ix_example_stream_profile_status')
        batch_op.drop_index('ix_example_stream_profile_logo_id')

    op.drop_table('example_stream_profile')
    with op.batch_alter_table('example_server_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_example_server_metric_server_sampled')

    op.drop_table('example_server_metric')
    with op.batch_alter_table('example_project', schema=None) as batch_op:
        batch_op.drop_index('ix_example_project_team_status')
        batch_op.drop_index('ix_example_project_priority')
        batch_op.drop_index('ix_example_project_is_active')

    op.drop_table('example_project')
    with op.batch_alter_table('example_team', schema=None) as batch_op:
        batch_op.drop_index('ix_example_team_region')
        batch_op.drop_index('ix_example_team_is_active')

    op.drop_table('example_team')
    op.drop_table('example_tag')
    with op.batch_alter_table('example_server', schema=None) as batch_op:
        batch_op.drop_index('ix_example_server_status')
        batch_op.drop_index('ix_example_server_region')

    op.drop_table('example_server')
    with op.batch_alter_table('example_logo', schema=None) as batch_op:
        batch_op.drop_index('ix_example_logo_name')
        batch_op.drop_index('ix_example_logo_country_available')

    op.drop_table('example_logo')
    # ### end Alembic commands ###
