export {
  DASHBOARD_MODAL_BACKDROP_CLASS as OLDMAN_MODAL_BACKDROP_CLASS,
  DASHBOARD_MODAL_BODY_OPEN_CLASS as OLDMAN_MODAL_BODY_OPEN_CLASS,
  DASHBOARD_MODAL_CONTENT_SELECTOR as OLDMAN_MODAL_CONTENT_SELECTOR,
  DASHBOARD_MODAL_DIALOG_SELECTOR as OLDMAN_MODAL_DIALOG_SELECTOR,
  DASHBOARD_MODAL_FOOTER_SELECTOR as OLDMAN_MODAL_FOOTER_SELECTOR,
  DASHBOARD_MODAL_OPEN_CLASS as OLDMAN_MODAL_OPEN_CLASS,
  DASHBOARD_MODAL_SURFACE_SELECTOR as OLDMAN_MODAL_SURFACE_SELECTOR,
  DASHBOARD_MODAL_TITLE_SELECTOR as OLDMAN_MODAL_TITLE_SELECTOR,
  DASHBOARD_MODAL_TRANSITION_FALLBACK_MS as OLDMAN_MODAL_TRANSITION_FALLBACK_MS,
  DashboardModal as OldmanModal
} from "oldman-web/dashboard/modal";
export type { DashboardModalOptions as OldmanModalOptions } from "oldman-web/dashboard/modal";
