"""create EPG management tables

Revision ID: 2e7c72c79afb
Revises:
Create Date: 2026-08-10 00:19:56.621745

Review upgrade() and downgrade() before applying this migration.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2e7c72c79afb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("epg_admin",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_channel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_key", sa.String(length=120), nullable=False),
        sa.Column("owner_country_code", sa.String(length=8), nullable=False),
        sa.Column("channel_id", sa.String(length=160).with_variant(sa.String(length=160, collation="utf8mb4_unicode_ci"), "mysql"), nullable=False),
        sa.Column("identity_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.SmallInteger(), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", name="uq_catalog_channel_channel_id"),
        info={"oldman_app_label": "epg_admin", "oldman_managed": True},
    )
    with op.batch_alter_table("catalog_channel", schema=None) as batch_op:
        batch_op.create_index("ix_catalog_channel_channel_key", ["channel_key"], unique=False)
        batch_op.create_index("ix_catalog_channel_owner_country_code", ["owner_country_code"], unique=False)
        batch_op.create_index("ix_catalog_channel_status", ["status"], unique=False)

    op.create_table(
        "epg_channelsepg",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("src_url", sa.String(length=200), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column("last_date", sa.Date(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("tvg_id", sa.String(length=120), nullable=True),
        sa.Column("tvg_id_lookup", sa.String(length=120), nullable=True),
        sa.Column("tvg_id_source", sa.String(length=32), nullable=False),
        sa.Column("tvg_id_confidence", sa.SmallInteger(), nullable=False),
        sa.Column("tvg_id_locked", sa.Boolean(), nullable=False),
        sa.Column("tvg_id_resolved_at", sa.DateTime(), nullable=True),
        sa.Column("tvg_id_reason", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        info={"oldman_app_label": "epg_admin", "oldman_managed": True},
    )
    with op.batch_alter_table("epg_channelsepg", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_epg_channelsepg_country"), ["country"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelsepg_hits"), ["hits"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelsepg_last_date"), ["last_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelsepg_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelsepg_src_url"), ["src_url"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelsepg_tvg_id"), ["tvg_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelsepg_tvg_id_lookup"), ["tvg_id_lookup"], unique=False)

    op.create_table(
        "catalog_feed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_channel_id", sa.Integer(), nullable=False),
        sa.Column("feed_suffix", sa.String(length=80), nullable=False),
        sa.Column("tvg_id", sa.String(length=240).with_variant(sa.String(length=240, collation="utf8mb4_unicode_ci"), "mysql"), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("accepted_names_text", sa.Text(), nullable=True),
        sa.Column("compatible_tvg_ids_text", sa.Text(), nullable=True),
        sa.Column("service_country_code", sa.String(length=8), nullable=True),
        sa.Column("region_code", sa.String(length=64), nullable=True),
        sa.Column("language_hints_text", sa.Text(), nullable=True),
        sa.Column("timezone_hints_text", sa.Text(), nullable=True),
        sa.Column("version_kind", sa.String(length=32), nullable=False),
        sa.Column("wikidata_qid", sa.String(length=32), nullable=True),
        sa.Column("wikipedia_title", sa.String(length=255), nullable=True),
        sa.Column("official_website", sa.String(length=1024), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_language", sa.String(length=16), nullable=True),
        sa.Column("description_source_type", sa.String(length=64), nullable=True),
        sa.Column("description_source_url", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.SmallInteger(), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["catalog_channel_id"], ["catalog_channel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("catalog_channel_id", "feed_suffix", name="uq_catalog_feed_channel_suffix"),
        sa.UniqueConstraint("tvg_id", name="uq_catalog_feed_tvg_id"),
        info={"oldman_app_label": "epg_admin", "oldman_managed": True},
    )
    with op.batch_alter_table("catalog_feed", schema=None) as batch_op:
        batch_op.create_index("ix_catalog_feed_catalog_channel_id", ["catalog_channel_id"], unique=False)
        batch_op.create_index("ix_catalog_feed_service_country_code", ["service_country_code"], unique=False)
        batch_op.create_index("ix_catalog_feed_status", ["status"], unique=False)
        batch_op.create_index("ix_catalog_feed_wikidata_qid", ["wikidata_qid"], unique=False)

    op.create_table(
        "epg_channelname",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("name_cn", sa.String(length=50), nullable=True),
        sa.Column("name_tw", sa.String(length=50), nullable=True),
        sa.Column("name_es", sa.String(length=50), nullable=True),
        sa.Column("logo", sa.String(length=100), nullable=False),
        sa.Column("logo_size", sa.Numeric(precision=64, scale=2), nullable=True),
        sa.Column("epg_id", sa.Integer(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("channel_order", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("last_date", sa.Date(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["epg_id"],
            ["epg_channelsepg.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        info={"oldman_app_label": "epg_admin", "oldman_managed": True},
    )
    with op.batch_alter_table("epg_channelname", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_epg_channelname_category_id"), ["category_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelname_channel_order"), ["channel_order"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelname_country_id"), ["country_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelname_epg_id"), ["epg_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelname_language_id"), ["language_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_channelname_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_epg_channelname_name_tw"), ["name_tw"], unique=False)

    op.create_table(
        "epg_epglist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=400), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["epg_channelsepg.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        info={"oldman_app_label": "epg_admin", "oldman_managed": True},
    )
    with op.batch_alter_table("epg_epglist", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_epg_epglist_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_epglist_start_date"), ["start_date"], unique=False)

    op.create_table(
        "catalog_logo_asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_feed_id", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("original_url", sa.String(length=1024), nullable=True),
        sa.Column("original_path", sa.String(length=512), nullable=False),
        sa.Column("normalized_path", sa.String(length=512), nullable=False),
        sa.Column("preview_path", sa.String(length=512), nullable=True),
        sa.Column("edge_map_path", sa.String(length=512), nullable=True),
        sa.Column("mask_map_path", sa.String(length=512), nullable=True),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("phash", sa.String(length=32), nullable=True),
        sa.Column("dhash", sa.String(length=32), nullable=True),
        sa.Column("edge_phash", sa.String(length=32), nullable=True),
        sa.Column("mask_phash", sa.String(length=32), nullable=True),
        sa.Column("visible_bbox_json", sa.Text(), nullable=True),
        sa.Column("quality_score", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["catalog_feed_id"], ["catalog_feed.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("catalog_feed_id", name="uq_catalog_logo_asset_feed"),
        info={"oldman_app_label": "epg_admin", "oldman_managed": True},
    )
    with op.batch_alter_table("catalog_logo_asset", schema=None) as batch_op:
        batch_op.create_index("ix_catalog_logo_asset_edge_phash", ["edge_phash"], unique=False)
        batch_op.create_index("ix_catalog_logo_asset_mask_phash", ["mask_phash"], unique=False)
        batch_op.create_index("ix_catalog_logo_asset_phash", ["phash"], unique=False)
        batch_op.create_index("ix_catalog_logo_asset_sha256", ["sha256"], unique=False)

    op.create_table(
        "upstream_source_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("catalog_feed_id", sa.Integer(), nullable=True),
        sa.Column("source_code", sa.String(length=64).with_variant(sa.String(length=64, collation="utf8mb4_bin"), "mysql"), nullable=False),
        sa.Column("source_record_key", sa.String(length=255).with_variant(sa.String(length=255, collation="utf8mb4_bin"), "mysql"), nullable=False),
        sa.Column("record_kind", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("primary_name", sa.String(length=255), nullable=True),
        sa.Column("logo_urls_text", sa.Text(), nullable=True),
        sa.Column("raw_payload", sa.Text(), nullable=False),
        sa.Column("raw_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("disappeared_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["catalog_feed_id"], ["catalog_feed.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_code", "source_record_key", name="uq_upstream_source_record_source_key"),
        info={"oldman_app_label": "epg_admin", "oldman_managed": True},
    )
    with op.batch_alter_table("upstream_source_record", schema=None) as batch_op:
        batch_op.create_index("ix_upstream_source_record_catalog_feed_id", ["catalog_feed_id"], unique=False)
        batch_op.create_index("ix_upstream_source_record_last_seen_at", ["last_seen_at"], unique=False)
        batch_op.create_index("ix_upstream_source_record_raw_hash", ["raw_hash"], unique=False)
        batch_op.create_index("ix_upstream_source_record_source_status", ["source_code", "status"], unique=False)

    op.create_table(
        "catalog_match_decision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_scope", sa.String(length=32), nullable=False),
        sa.Column("source_record_id", sa.Integer(), nullable=True),
        sa.Column("catalog_channel_id", sa.Integer(), nullable=True),
        sa.Column("catalog_feed_id", sa.Integer(), nullable=True),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["catalog_channel_id"], ["catalog_channel.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["catalog_feed_id"], ["catalog_feed.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_record_id"], ["upstream_source_record.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        info={"oldman_app_label": "epg_admin", "oldman_managed": True},
    )
    with op.batch_alter_table("catalog_match_decision", schema=None) as batch_op:
        batch_op.create_index("ix_catalog_match_decision_catalog_channel_id", ["catalog_channel_id"], unique=False)
        batch_op.create_index("ix_catalog_match_decision_catalog_feed_id", ["catalog_feed_id"], unique=False)
        batch_op.create_index("ix_catalog_match_decision_scope", ["decision_scope"], unique=False)
        batch_op.create_index("ix_catalog_match_decision_source_record_id", ["source_record_id"], unique=False)

    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('catalog_channel', 'epg_admin', TRUE, '2e7c72c79afb')"
    )
    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('epg_channelsepg', 'epg_admin', TRUE, '2e7c72c79afb')"
    )
    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('catalog_feed', 'epg_admin', TRUE, '2e7c72c79afb')"
    )
    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('epg_channelname', 'epg_admin', TRUE, '2e7c72c79afb')"
    )
    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('epg_epglist', 'epg_admin', TRUE, '2e7c72c79afb')"
    )
    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('catalog_logo_asset', 'epg_admin', TRUE, '2e7c72c79afb')"
    )
    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('upstream_source_record', 'epg_admin', TRUE, '2e7c72c79afb')"
    )
    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('catalog_match_decision', 'epg_admin', TRUE, '2e7c72c79afb')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'catalog_match_decision' AND app_label = 'epg_admin'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'upstream_source_record' AND app_label = 'epg_admin'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'catalog_logo_asset' AND app_label = 'epg_admin'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'epg_epglist' AND app_label = 'epg_admin'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'epg_channelname' AND app_label = 'epg_admin'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'catalog_feed' AND app_label = 'epg_admin'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'epg_channelsepg' AND app_label = 'epg_admin'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'catalog_channel' AND app_label = 'epg_admin'")
    with op.batch_alter_table("catalog_match_decision", schema=None) as batch_op:
        batch_op.drop_index("ix_catalog_match_decision_source_record_id")
        batch_op.drop_index("ix_catalog_match_decision_scope")
        batch_op.drop_index("ix_catalog_match_decision_catalog_feed_id")
        batch_op.drop_index("ix_catalog_match_decision_catalog_channel_id")

    op.drop_table("catalog_match_decision")
    with op.batch_alter_table("upstream_source_record", schema=None) as batch_op:
        batch_op.drop_index("ix_upstream_source_record_source_status")
        batch_op.drop_index("ix_upstream_source_record_raw_hash")
        batch_op.drop_index("ix_upstream_source_record_last_seen_at")
        batch_op.drop_index("ix_upstream_source_record_catalog_feed_id")

    op.drop_table("upstream_source_record")
    with op.batch_alter_table("catalog_logo_asset", schema=None) as batch_op:
        batch_op.drop_index("ix_catalog_logo_asset_sha256")
        batch_op.drop_index("ix_catalog_logo_asset_phash")
        batch_op.drop_index("ix_catalog_logo_asset_mask_phash")
        batch_op.drop_index("ix_catalog_logo_asset_edge_phash")

    op.drop_table("catalog_logo_asset")
    with op.batch_alter_table("epg_epglist", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_epg_epglist_start_date"))
        batch_op.drop_index(batch_op.f("ix_epg_epglist_channel_id"))

    op.drop_table("epg_epglist")
    with op.batch_alter_table("epg_channelname", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_epg_channelname_name_tw"))
        batch_op.drop_index(batch_op.f("ix_epg_channelname_name"))
        batch_op.drop_index(batch_op.f("ix_epg_channelname_language_id"))
        batch_op.drop_index(batch_op.f("ix_epg_channelname_epg_id"))
        batch_op.drop_index(batch_op.f("ix_epg_channelname_country_id"))
        batch_op.drop_index(batch_op.f("ix_epg_channelname_channel_order"))
        batch_op.drop_index(batch_op.f("ix_epg_channelname_category_id"))

    op.drop_table("epg_channelname")
    with op.batch_alter_table("catalog_feed", schema=None) as batch_op:
        batch_op.drop_index("ix_catalog_feed_wikidata_qid")
        batch_op.drop_index("ix_catalog_feed_status")
        batch_op.drop_index("ix_catalog_feed_service_country_code")
        batch_op.drop_index("ix_catalog_feed_catalog_channel_id")

    op.drop_table("catalog_feed")
    with op.batch_alter_table("epg_channelsepg", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_epg_channelsepg_tvg_id_lookup"))
        batch_op.drop_index(batch_op.f("ix_epg_channelsepg_tvg_id"))
        batch_op.drop_index(batch_op.f("ix_epg_channelsepg_src_url"))
        batch_op.drop_index(batch_op.f("ix_epg_channelsepg_name"))
        batch_op.drop_index(batch_op.f("ix_epg_channelsepg_last_date"))
        batch_op.drop_index(batch_op.f("ix_epg_channelsepg_hits"))
        batch_op.drop_index(batch_op.f("ix_epg_channelsepg_country"))

    op.drop_table("epg_channelsepg")
    with op.batch_alter_table("catalog_channel", schema=None) as batch_op:
        batch_op.drop_index("ix_catalog_channel_status")
        batch_op.drop_index("ix_catalog_channel_owner_country_code")
        batch_op.drop_index("ix_catalog_channel_channel_key")

    op.drop_table("catalog_channel")
    # ### end Alembic commands ###
